# Generated by Django 4.2.7 on 2024-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', '관리자'), ('instructor', '강사'), ('student', '수강생')], default='student', max_length=10),
        ),
    ]
