# Generated by Django 4.2.7 on 2024-11-26 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('emergency_contact', models.CharField(blank=True, max_length=15, verbose_name='비상연락처')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('note', models.TextField(blank=True, verbose_name='특이사항')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='가입일')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='최근 방문일')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '수강생 프로필',
                'verbose_name_plural': '수강생 프로필 목록',
                'db_table': 'student_profile',
            },
        ),
    ]
