# Generated by Django 4.2.7 on 2024-11-26 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_expiry', models.BooleanField(default=True, verbose_name='수강권 만료 알림')),
                ('class_reminder', models.BooleanField(default=True, verbose_name='수업 알림')),
                ('makeup_status', models.BooleanField(default=True, verbose_name='보강 상태 알림')),
                ('pause_status', models.BooleanField(default=True, verbose_name='일시정지 상태 알림')),
                ('announcement', models.BooleanField(default=True, verbose_name='공지사항 알림')),
                ('attendance', models.BooleanField(default=True, verbose_name='출결 알림')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='이메일 알림')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='푸시 알림')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정 목록',
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('subscription_expiry', '수강권 만료 예정'), ('class_reminder', '수업 알림'), ('makeup_status', '보강 신청 상태 변경'), ('pause_status', '일시정지 신청 상태 변경'), ('announcement', '공지사항'), ('attendance', '출결 알림')], max_length=20, verbose_name='알림 종류')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='관련 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
