# Generated by Django 4.2.7 on 2024-11-26 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('days', '기간제'), ('counts', '횟수제')], max_length=10, verbose_name='수강권 종류')),
                ('status', models.CharField(choices=[('active', '이용중'), ('paused', '일시정지'), ('expired', '만료'), ('cancelled', '취소')], default='active', max_length=10, verbose_name='상태')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('total_classes', models.PositiveIntegerField(blank=True, null=True, verbose_name='전체 수업 횟수')),
                ('remaining_classes', models.PositiveIntegerField(blank=True, null=True, verbose_name='남은 수업 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dance_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.danceclass', verbose_name='수업')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '수강권',
                'verbose_name_plural': '수강권 목록',
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('reason', models.TextField(verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='수강권')),
            ],
            options={
                'verbose_name': '수강권 일시정지',
                'verbose_name_plural': '수강권 일시정지 목록',
                'db_table': 'subscription_pause',
            },
        ),
    ]
