# Generated by Django 4.2.7 on 2024-11-26 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': '수강권', 'verbose_name_plural': '수강권 목록'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionpause',
            options={'ordering': ['-created_at'], 'verbose_name': '수강권 일시정지', 'verbose_name_plural': '수강권 일시정지 목록'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(default='card', max_length=50, verbose_name='결제 방법'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_paid',
            field=models.PositiveIntegerField(default=30000, verbose_name='결제 금액'),
        ),
        migrations.AlterField(
            model_name='subscriptionpause',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='subscriptions.subscription', verbose_name='수강권'),
        ),
    ]
