# Generated by Django 4.2.7 on 2024-11-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(verbose_name='원래 수업일')),
                ('makeup_date', models.DateField(verbose_name='보강 수업일')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절'), ('completed', '완료')], default='pending', max_length=10, verbose_name='상태')),
                ('reason', models.TextField(verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makeup_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makeup_classes', to='classes.classschedule', verbose_name='보강 수업')),
                ('original_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_classes', to='classes.classschedule', verbose_name='원래 수업')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '보강',
                'verbose_name_plural': '보강 목록',
                'db_table': 'makeup_class',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('status', models.CharField(choices=[('present', '출석'), ('absent', '결석'), ('late', '지각'), ('excused', '사유결석'), ('makeup', '보강')], max_length=10, verbose_name='출결 상태')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dance_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.danceclass', verbose_name='수업')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.classschedule', verbose_name='수업 일정')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '출결',
                'verbose_name_plural': '출결 목록',
                'db_table': 'attendance',
                'unique_together': {('student', 'dance_class', 'date')},
            },
        ),
    ]
