# Generated by Django 4.2.7 on 2024-11-26 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='수업명')),
                ('description', models.TextField(blank=True, verbose_name='수업 설명')),
                ('capacity', models.PositiveIntegerField(verbose_name='정원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'user_type': 'instructor'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='강사')),
            ],
            options={
                'verbose_name': '수업',
                'verbose_name_plural': '수업 목록',
                'db_table': 'dance_class',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('dance_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.danceclass', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수업 일정',
                'verbose_name_plural': '수업 일정 목록',
                'db_table': 'class_schedule',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
