# Generated by Django 4.2.7 on 2024-11-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='room',
            field=models.CharField(default='메인 연습실', max_length=50, verbose_name='강의실'),
        ),
        migrations.AddField(
            model_name='danceclass',
            name='difficulty',
            field=models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], default='beginner', max_length=20, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='danceclass',
            name='price_per_month',
            field=models.PositiveIntegerField(default=100000, verbose_name='월 수강료'),
        ),
        migrations.AddField(
            model_name='danceclass',
            name='status',
            field=models.CharField(choices=[('active', '운영중'), ('pending', '준비중'), ('closed', '종료')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='dance_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.danceclass', verbose_name='수업'),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.UniqueConstraint(fields=('dance_class', 'weekday', 'start_time'), name='unique_class_schedule'),
        ),
    ]
